language: python
cache: pip
python:
  - "2.7"
  - "3.5"
sudo: required
before_install:
  - sudo -H pip install pytest pytest-cov
  - sudo -H pip install urllib3[secure] coveralls
install:
  - sudo -H pip install -r requirements.txt
script:
  - py.test --cov=pseudosci
after_success:
  - coveralls
