language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
before_install:
  - sudo -H pip install pytest pytest-cov coverage urllib3[secure] coveralls
install:
  - sudo -H pip install -r requirements.txt
script:
  - coverage run --source pseudosci -m py.test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e15c1b6de9d180d2eafe
    on_success: change
    on_failure: always
    on_start: never
