langage: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install --user -r requirements.txt
script:
  - py.test
after_success:
  - if [[ $ENV == python=3.6* ]]; then
        coveralls;
    fi