language: python
cache: pip
python:
  - "2.7"
  - "3.5"
sudo: required
before_install:
  - sudo -H pip install pytest pytest-cov urllib3[secure] coveralls
install:
  - sudo -H pip install -r requirements.txt
script:
  - py.test --cov-report= --cov=pseudosci
after_success:
  - coveralls
