language: python
cache: pip
python: "3.5"
before_install:
  - pip install --user pytest pytest-cov
  - pip install --user coveralls
install:
  - pip install --user -r requirements.txt
script:
  - pytest
after_success:
  - coveralls
