language: python
cache: pip
python: "3.6"
sudo: required
before_install:
  - sudo pip install pytest pytest-cov
  - sudo pip install coveralls
install:
  - sudo pip install -r requirements.txt
script:
  - pytest
after_success:
  - coveralls
